import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import AdminHeader from "../../../components/admin/AdminHeader";
import SideBar from "../../../components/admin/SideBar";

export const metadata: Metadata = {
  title: "Admin Dashboard | Dreamline Safaris",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <div className="h-screen w-screen overflow-hidden">
        <AdminHeader />
        <SideBar />
        {/* main content area */}
        <main className="pt-16 ml-16 md:ml-52 bg-slate-700 h-full overflow-y-auto p-4 text-gray-200">
          {children}
        </main>
      </div>
    </ClerkProvider>
  );
}
